disabled_rules: # rule identifiers to exclude from running
  - colon
  - comma
  - control_statement
opt_in_rules: # some rules are only opt-in
  - empty_count
  - missing_docs
  - vertical_parameter_alignment_on_call
  - extension_access_modifier
  - multiline_parameters

  # Find all the available rules by running:
  # swiftlint rules
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods

# configurable rules can be customized from this configuration file
# binary rules can set their severity level

cyclomatic_complexity:
  - 20 # warning
  - 30 # error

force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 160
# they can set both implicitly with an array

function_body_length:
  - 100 # warning
  - 200 # error

type_body_length:
  - 300 # warning
  - 400 # error
# or they can set both explicitly
file_length:
  warning: 500
  error: 1200
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 60
    error: 100
  excluded:
    - Log
identifier_name:
  min_length: # only min_length
    error: 3 # only error
  excluded:
    - id
    - key
    - url

statement_position:
  statement_mode: uncuddled_else
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)

object_literal:
  code_literal: false
  image_literal: false

